// js/data.js

const deliveryData = [
    // Slot 1
    { slot: 1, name: 'Ney', order: 5000, send: 3670, statusOverride: 'fail' },
    { slot: 1, name: 'Aelia', order: 1900, send: 940, statusOverride: 'fail' },
    { slot: 1, name: 'Anna', order: 1080, send: 640 },
    { slot: 1, name: 'Feng', order: 230, send: 220, statusOverride: 'fail' },
    { slot: 1, name: 'Tuna 2', order: 360, send: 220 },
    { slot: 1, name: 'Unii', order: 400, send: 170 },
    { slot: 1, name: 'archa', order: 460, send: 180 },
    { slot: 1, name: 'Zel', order: 340, send: 80 },
    { slot: 1, name: 'Raine', order: 340, send: 60 },

    // Slot 2
    { slot: 2, name: 'Angel2', order: 600, send: 540, statusOverride: 'fail' },
    { slot: 2, name: 'Autumn', order: 850, send: 375, statusOverride: 'fail' },
    { slot: 2, name: 'Rachel', order: 400, send: 340 },
    { slot: 2, name: 'Honey bear', order: 1400, send: 340 }, // Send diperbarui, status ❌ dihapus
    { slot: 2, name: 'Cem', order: 660, send: 340 },
    { slot: 2, name: 'Niz', order: 720, send: 420 },
    { slot: 2, name: 'yulii', order: 400, send: 200 },
    { slot: 2, name: 'Ira', order: 500, send: 140 },
    { slot: 2, name: 'Rani', order: 420, send: 20 }, // Pembeli baru

    // Slot 3
    { slot: 3, name: 'Aze', order: 570, send: 520, statusOverride: 'fail' },
    { slot: 3, name: 'Lili', order: 360, send: 260 },
    { slot: 3, name: 'Onde mande', order: 800, send: 160, statusOverride: 'fail' },
    { slot: 3, name: 'Lia', order: 400, send: 200 },
    { slot: 3, name: 'Cici', order: 100, send: 60, statusOverride: 'fail' },
    { slot: 3, name: 'Fio', order: 180, send: 20 },
    { slot: 3, name: 'Fia', order: 500, send: 140 },

    // Riwayat Orderan Selesai
    { slot: 'completed', name: 'Tuna', order: 360, send: 360 },
    { slot: 'completed', name: 'Asha', order: 120, send: 120 },
    { slot: 'completed', name: 'eliane', order: 120, send: 120 },
    { slot: 'completed', name: 'Louis', order: 310, send: 310 },
    { slot: 'completed', name: 'Aya', order: 860, send: 860 },
    { slot: 'completed', name: 'Rezz', order: 350, send: 350 },
    { slot: 'completed', name: 'Yaya', order: 200, send: 200 },
    { slot: 'completed', name: 'Diyy', order: 640, send: 640 },
    { slot: 'completed', name: 'Luna', order: 800, send: 800 },
    { slot: 'completed', name: 'Ryu', order: 320, send: 320 },
    { slot: 'completed', name: 'Idnes', order: 320, send: 320 },
    { slot: 'completed', name: 'Risma', order: 120, send: 120 },
    { slot: 'completed', name: 'Alana', order: 320, send: 320 },
    { slot: 'completed', name: 'Zee', order: 400, send: 400 },
    { slot: 'completed', name: 'futaba', order: 140, send: 140 },
    { slot: 'completed', name: 'Sena', order: 570, send: 570 },
    { slot: 'completed', name: 'Al', order: 320, send: 320 },
    { slot: 'completed', name: 'Ave', order: 220, send: 240 },
    { slot: 'completed', name: 'Kai', order: 220, send: 220 },
    { slot: 'completed', name: 'Rei', order: 220, send: 220 },
    { slot: 'completed', name: 'Araba', order: 150, send: 150 },
    { slot: 'completed', name: 'Nayla', order: 530, send: 530 },
    { slot: 'completed', name: 'Purili', order: 320, send: 320 },
    { slot: 'completed', name: 'Rain', order: 320, send: 320 },
    { slot: 'completed', name: 'Alip', order: 320, send: 320 },
    { slot: 'completed', name: 'Anggi', order: 320, send: 320 },
    { slot: 'completed', name: 'Hira', order: 360, send: 377 },
    { slot: 'completed', name: 'Amanda', order: 80, send: 80 },
    { slot: 'completed', name: 'bulilisso', order: 80, send: 80 },
    { slot: 'completed', name: 'Tsabyy', order: 200, send: 200 },
    { slot: 'completed', name: 'Harbie', order: 200, send: 200 },
    { slot: 'completed', name: 'Fida', order: 100, send: 103 },
    { slot: 'completed', name: 'Vyan', order: 80, send: 83 },
    { slot: 'completed', name: 'Ayu', order: 1000, send: 1003 },
    { slot: 'completed', name: 'Anna', order: 600, send: 603 },
    { slot: 'completed', name: 'Zee', order: 150, send: 153 },
    { slot: 'completed', name: 'Nanda', order: 210, send: 213 },
    { slot: 'completed', name: 'Alvin', order: 210, send: 213 },
    { slot: 'completed', name: 'Ira', order: 150, send: 153 },
    { slot: 'completed', name: 'Kael', order: 120, send: 123 },
    { slot: 'completed', name: 'Xen', order: 210, send: 213 },
    { slot: 'completed', name: 'Lusi', order: 600, send: 603 },
    { slot: 'completed', name: 'Sea', order: 150, send: 157 },
    { slot: 'completed', name: 'Raine', order: 420, send: 420 }
];
     
