// js/data.js
const deliveryData = [
    // Slot 1
    { id: 1, name: 'Ney', order: 5000, send: 3750, slot: 1, number: '', notes: '', statusOverride: null },
    { id: 2, name: 'Aelia', order: 1900, send: 1020, slot: 1, number: '', notes: '', statusOverride: null },
    { id: 3, name: 'Anna', order: 1080, send: 720, slot: 1, number: '', notes: '', statusOverride: null },
    { id: 4, name: 'Feng', order: 230, send: 220, slot: 1, number: '', notes: '', statusOverride: 'fail' },
    { id: 5, name: 'Tuna 2', order: 360, send: 240, slot: 1, number: '', notes: '', statusOverride: 'fail' },
    { id: 6, name: 'Unii', order: 400, send: 240, slot: 1, number: '', notes: '', statusOverride: null },
    { id: 7, name: 'Archa', order: 460, send: 260, slot: 1, number: '', notes: '', statusOverride: null },
    { id: 8, name: 'Zel', order: 340, send: 160, slot: 1, number: '', notes: '', statusOverride: null },
    { id: 9, name: 'Raine', order: 340, send: 140, slot: 1, number: '', notes: '', statusOverride: null },

    // Slot 2
    { id: 10, name: 'Angel2', order: 600, send: 540, slot: 2, number: '', notes: '', statusOverride: 'fail' },
    { id: 11, name: 'Autumn', order: 850, send: 375, slot: 2, number: '', notes: '', statusOverride: 'fail' },
    { id: 12, name: 'Rachel', order: 400, send: 340, slot: 2, number: '', notes: '', statusOverride: 'fail' },
    { id: 13, name: 'Honey bear', order: 1400, send: 420, slot: 2, number: '', notes: '', statusOverride: null },
    { id: 14, name: 'Cem', order: 660, send: 420, slot: 2, number: '', notes: '', statusOverride: null },
    { id: 15, name: 'Niz', order: 720, send: 460, slot: 2, number: '', notes: '', statusOverride: 'fail' },
    { id: 16, name: 'Yulii', order: 400, send: 280, slot: 2, number: '', notes: '', statusOverride: null },
    { id: 17, name: 'Ira', order: 500, send: 220, slot: 2, number: '', notes: '', statusOverride: null },
    { id: 18, name: 'Rani', order: 420, send: 80, slot: 2, number: '', notes: '', statusOverride: null },
    { id: 19, name: 'Klara', order: 420, send: 80, slot: 2, number: '', notes: '', statusOverride: null },
    { id: 20, name: 'Asha', order: 180, send: 80, slot: 2, number: '', notes: '', statusOverride: null },
    { id: 21, name: 'Eliane', order: 180, send: 80, slot: 2, number: '', notes: '', statusOverride: null },

    // Slot 3
    { id: 22, name: 'Aze', order: 570, send: 560, slot: 3, number: '', notes: '', statusOverride: 'fail' },
    { id: 23, name: 'Lili', order: 360, send: 300, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 24, name: 'Onde mande', order: 800, send: 180, slot: 3, number: '', notes: '', statusOverride: 'fail' },
    { id: 25, name: 'Lia', order: 400, send: 280, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 26, name: 'Fio', order: 180, send: 100, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 27, name: 'Rezz', order: 180, send: 60, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 28, name: 'Kazuhime', order: 180, send: 80, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 29, name: 'Rendy', order: 310, send: 80, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 30, name: 'Saki', order: 120, send: 40, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 31, name: 'Ian', order: 1100, send: 20, slot: 3, number: '', notes: '', statusOverride: null },
    { id: 32, name: 'Fia', order: 500, send: 300, slot: 3, number: '', notes: '', statusOverride: null },

    // Completed
    { id: 33, name: 'Cici', order: 100, send: 100, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 34, name: 'Tuna', order: 360, send: 360, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 35, name: 'Louis', order: 310, send: 310, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 36, name: 'Aya', order: 860, send: 860, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 37, name: 'Yaya', order: 200, send: 200, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 38, name: 'Diyy', order: 640, send: 640, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 39, name: 'Luna', order: 800, send: 800, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 40, name: 'Ryu', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 41, name: 'Idnes', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 42, name: 'Risma', order: 120, send: 120, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 43, name: 'Alana', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 44, name: 'Zee', order: 400, send: 400, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 45, name: 'futaba', order: 140, send: 140, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 46, name: 'Sena', order: 570, send: 570, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 47, name: 'Al', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 48, name: 'Ave', order: 220, send: 240, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 49, name: 'Kai', order: 220, send: 220, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 50, name: 'Rei', order: 220, send: 220, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 51, name: 'Araba', order: 150, send: 150, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 52, name: 'Nayla', order: 530, send: 530, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 53, name: 'Purili', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 54, name: 'Rain', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 55, name: 'Alip', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 56, name: 'Anggi', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 57, name: 'Hira', order: 360, send: 377, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 58, name: 'Amanda', order: 80, send: 80, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 59, name: 'bulilisso', order: 80, send: 80, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 60, name: 'Tsabyy', order: 200, send: 200, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 61, name: 'Harbie', order: 200, send: 200, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 62, name: 'Fida', order: 100, send: 103, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 63, name: 'Vyan', order: 80, send: 83, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 64, name: 'Ayu', order: 1000, send: 1003, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 65, name: 'Anna', order: 600, send: 603, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 66, name: 'Zee', order: 150, send: 153, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 67, name: 'Nanda', order: 210, send: 213, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 68, name: 'Alvin', order: 210, send: 213, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 69, name: 'Ira', order: 150, send: 153, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 70, name: 'Kael', order: 120, send: 123, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 71, name: 'Xen', order: 210, send: 213, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 72, name: 'Lusi', order: 600, send: 603, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 73, name: 'Sea', order: 150, send: 157, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 74, name: 'Rani', order: 320, send: 320, slot: 'completed', number: '', notes: '', statusOverride: null },
    { id: 75, name: 'Raine', order: 420, send: 420, slot: 'completed', number: '', notes: '', statusOverride: null }
];
