const STORE_CONFIG = {
  name: "BALILSTORE",
  tagline: "Top-Up Heart Resmi & Terpercaya",
  game: "Sky: Children of the Light",
  whatsapp: "6285363625159",
  waGroup: "https://chat.whatsapp.com/JelUbSutCNVAIOtcGoy6Uy?s=cl&p=a&mlu=4",
  dailyCapacity: 30,
  heroImage: "assets/hero-bg.jpg",
  qrisImage: "assets/qris.png",
  currency: {
    idr: { code: "IDR", symbol: "Rp", locale: "id-ID" },
    usd: { code: "USD", symbol: "$", locale: "en-US" },
  },
  paypal: {
    email: "balilstore@paypal.com",
    link: "https://paypal.me/balilstore",
  },
  social: {
    whatsapp: "https://wa.me/6285363625159",
    instagram: "https://www.instagram.com/bahlilwax/",
    tiktok: "https://tiktok.com/@balilstore",
  },
  stats: {
    customers: "1.200+",
    orders: "5.800+",
    rating: "4.9",
    uptime: "99%",
  },
};

const HEART_PACKAGES = [
  {
    id: "pkg-100",
    hearts: 100,
    bonus: 0,
    label: "Starter",
    tag: null,
    popular: false,
    priceIDR: 12000,
    priceUSD: 1.0,
    description: "Sempurna untuk memulai koleksi Heart pertamamu.",
    estimateDays: 4,
    perHeartIDR: 120,
  },
  {
    id: "pkg-200",
    hearts: 200,
    bonus: 0,
    label: "Explorer",
    tag: null,
    popular: false,
    priceIDR: 22000,
    priceUSD: 1.8,
    description: "Pilihan ideal untuk petualang aktif tiap minggu.",
    estimateDays: 7,
    perHeartIDR: 110,
  },
  {
    id: "pkg-300",
    hearts: 300,
    bonus: 0,
    label: "Dreamer",
    tag: "TERLARIS",
    popular: true,
    priceIDR: 32000,
    priceUSD: 2.5,
    description: "Nilai terbaik — favorit ribuan pelanggan BALILSTORE.",
    estimateDays: 10,
    perHeartIDR: 107,
  },
  {
    id: "pkg-450",
    hearts: 450,
    bonus: 0,
    label: "Wanderer",
    tag: null,
    popular: false,
    priceIDR: 45000,
    priceUSD: 3.5,
    description: "Raih semua item impianmu tanpa khawatir kehabisan.",
    estimateDays: 15,
    perHeartIDR: 100,
  },
  {
    id: "pkg-600",
    hearts: 600,
    bonus: 0,
    label: "Champion",
    tag: "HEMAT",
    popular: false,
    priceIDR: 55000,
    priceUSD: 4.2,
    description: "Untuk kamu yang serius menjelajahi seluruh dunia Sky.",
    estimateDays: 20,
    perHeartIDR: 92,
  },
  {
    id: "pkg-800",
    hearts: 800,
    bonus: 20,
    label: "Legend",
    tag: "BONUS +20",
    popular: false,
    priceIDR: 65000,
    priceUSD: 5.0,
    description: "Paket premium — dapatkan 820 Heart dengan harga spesial!",
    estimateDays: 27,
    perHeartIDR: 79,
  },
];

const DEMO_ORDERS = [
  {
    id: "balil-1001",
    nickname: "SkyWalker",
    package: "300 Heart",
    packageId: "pkg-300",
    status: "completed",
    heartsSent: 300,
    heartsTotal: 300,
    queuePosition: 0,
    date: "2025-06-10",
  },
  {
    id: "balil-1024",
    nickname: "LunaChild",
    package: "450 Heart",
    packageId: "pkg-450",
    status: "processing",
    heartsSent: 90,
    heartsTotal: 450,
    queuePosition: 2,
    date: "2025-06-13",
  },
  {
    id: "balil-1031",
    nickname: "AuroraSky",
    package: "200 Heart",
    packageId: "pkg-200",
    status: "queued",
    heartsSent: 0,
    heartsTotal: 200,
    queuePosition: 5,
    date: "2025-06-13",
  },
  {
    id: "balil-1042",
    nickname: "StarDrifter",
    package: "800 Heart",
    packageId: "pkg-800",
    status: "processing",
    heartsSent: 60,
    heartsTotal: 820,
    queuePosition: 3,
    date: "2025-06-13",
  },
];

const STATUS_META = {
  completed:  { text: "Selesai",          color: "#4ade80", icon: "✓", bg: "rgba(74,222,128,0.08)"  },
  processing: { text: "Sedang Diproses",  color: "#DEB068", icon: "↻", bg: "rgba(222,176,104,0.08)" },
  queued:     { text: "Dalam Antrean",    color: "#9BB7D0", icon: "◷", bg: "rgba(155,183,208,0.08)" },
  notfound:   { text: "Tidak Ditemukan",  color: "#f87171", icon: "✗", bg: "rgba(248,113,113,0.08)" },
};

const REVIEWS = [
  { name: "Rania S.",     avatar: "R", stars: 5, date: "12 Jun 2025", pkg: "300 Heart", text: "Prosesnya cepet banget, ga sampe 2 hari udah masuk semua. Admin ramah dan responsif. Pasti balik lagi!" },
  { name: "Kevin A.",     avatar: "K", stars: 5, date: "10 Jun 2025", pkg: "800 Heart", text: "Udah langganan dari bulan lalu. Harganya paling murah se-Indonesia, bonus +20 Heart itu worth banget!" },
  { name: "Putri D.",     avatar: "P", stars: 5, date: "08 Jun 2025", pkg: "450 Heart", text: "Awalnya ragu, tapi ternyata legit banget. Heart langsung masuk, ga perlu kasih password sama sekali. 10/10!" },
  { name: "Arif M.",      avatar: "A", stars: 4, date: "05 Jun 2025", pkg: "200 Heart", text: "Oke banget, sesuai estimasi. Minta update status via WA langsung direspons cepat." },
  { name: "Nadia R.",     avatar: "N", stars: 5, date: "03 Jun 2025", pkg: "600 Heart", text: "Toko paling trusted buat top-up Heart. Sudah 3x beli, ga pernah kecewa. Rekomen ke semua teman!" },
  { name: "Dimas F.",     avatar: "D", stars: 5, date: "01 Jun 2025", pkg: "300 Heart", text: "Paket Dreamer emang terbaik! Harga pas, Heart cepat masuk. Terima kasih BALILSTORE!" },
];

const FAQ_DATA = [
  {
    q: "Berapa lama proses pengiriman Heart?",
    a: "Maksimal 30 Heart per hari sesuai batas sistem game Sky. Estimasi waktu tertera di setiap paket. Pesanan diproses setiap hari pukul 08.00–22.00 WIB termasuk weekend.",
  },
  {
    q: "Apakah perlu share password akun Sky?",
    a: "Tidak perlu! Kami hanya membutuhkan Nickname atau Friend Code kamu. Akun Sky kamu 100% aman karena Heart dikirim melalui mekanisme gifting resmi dalam game.",
  },
  {
    q: "Bagaimana cara melakukan pemesanan?",
    a: "Pilih paket yang kamu inginkan, tambahkan ke keranjang, klik Checkout, ikuti instruksi pembayaran (QRIS/PayPal), lalu konfirmasi via WhatsApp Admin. Sesederhana itu!",
  },
  {
    q: "Apakah bisa pesan lebih dari 1 paket sekaligus?",
    a: "Bisa! Kamu bisa menambahkan beberapa paket ke keranjang belanja dan checkout sekaligus. Admin akan menggabungkan pesananmu menjadi satu urutan pengiriman.",
  },
  {
    q: "Apakah ada jaminan refund?",
    a: "Ya, kami memberikan jaminan refund penuh jika pesanan terbukti gagal dan tidak dapat diproses ulang dalam 7 hari kalender. Lihat halaman Ketentuan untuk detail lengkap.",
  },
  {
    q: "Tersedia pembayaran apa saja?",
    a: "IDR: QRIS (GoPay, OVO, DANA, ShopeePay, semua mobile banking). USD: PayPal Merchant. Pilih sesuai lokasi dan preferensimu via tombol IDR/USD di navbar.",
  },
];
